# Copyright 2026 The Earth AI Remote Sensing Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""API for few-shot retrieval.

This is the entry point for the few-shot retrieval API.
"""

import abc
import dataclasses
from typing import Mapping, Optional, Sequence

import numpy as np


@dataclasses.dataclass(frozen=True)
class ZeroShotExample:
  """A single example that is produced by a zero-shot model.

  This class holds a single detection or data point, typically generated by a
  large, general-purpose zero-shot model. For zero-shot object detection
  models, a ZeroShotExample represents a single detected object.
  ZeroShotExamples are inputs for training a specialized few-shot model.

  Attributes:
    embedding: The feature vector (embedding) for this example, as returned by
      the zero-shot model. This is the primary data used for similarity
      comparisons and classification.
    score: The similarity score from the zero-shot model, indicating how certain
      it was about the initial detection.
    label: An optional binary label for the example. Initially `None`, this
      label is set by the user and is used to train the few-shot model. Allowed
      values are None, `0` and `1`.
    image_id: An optional unique identifier for the source image.
    crop: An optional crop of the detection from the source image. It can be
      used for visualization purposes and is expected to be a uint8 numpy array
      of shape (height, width, 3).
  """

  embedding: np.ndarray
  score: float
  label: Optional[int] = None
  image_id: Optional[bytes] = None
  crop: Optional[np.ndarray] = None


class AbstractFewShotClassifier(abc.ABC):
  """Abstract base class for a few-shot classifier.

  Implementations of this class are responsible for taking feature embeddings
  and producing binary classification predictions or confidence scores.
  Typically, instances are created as the output of an
  `AbstractFewShotAlgorithm`.
  """

  @abc.abstractmethod
  def classify(self, embeddings: np.ndarray) -> np.ndarray:
    """Classifies new embeddings.

    Args:
      embeddings: The embeddings of the examples to classify. The embeddings are
        expected to be of size (num_examples, embedding_dim).

    Returns:
      The predicted integer labels for the embeddings. The labels are expected
      to be of size (num_examples,) and to have binary values, either 0 or 1.
    """
    raise NotImplementedError()

  @abc.abstractmethod
  def score_confidence(self, embeddings: np.ndarray) -> np.ndarray:
    """Returns the confidence scores for the embeddings.

    Args:
      embeddings: The embeddings of the examples to score. The embeddings are
        expected to be of size (num_examples, embedding_dim).

    Returns:
      The confidence scores for the embeddings.
    """
    raise NotImplementedError()


class AbstractFewShotAlgorithm(abc.ABC):
  """Abstract base class for a few-shot algorithm.

  This class defines the interface for an active learning workflow that
  iteratively improves a classification model.

  The core methods are:
  - `get_indices_for_annotation`: Identifies which unlabeled examples the
    algorithm wants the user to label next.
  - `train_few_shot_model`: Creates a `FewShotClassifier` using the gathered
    annotations.
  """

  @abc.abstractmethod
  def get_indices_for_annotation(
      self,
      zero_shot_examples: Sequence[ZeroShotExample],
      number_of_samples: int,
  ) -> Sequence[int]:
    """Selects the most informative examples that need user labels.

    The embeddings and scores of the examples in `zero_shot_examples` are
    analyzed, and a subset of them is selected for annotation.

    Implementations should return a subset that when labeled, will be most
    useful for training a few shot classifier.

    Callers of this method should update the `label` field of the selected
    examples based on the user's input, and use them in a call to the
    `train_few_shot_model` method.

    Args:
      zero_shot_examples: A sequence of candidate examples.
      number_of_samples: The desired number of examples to be labeled.

    Returns:
      A sequence of integer indices corresponding to the examples in the
      `zero_shot_examples` list that should be presented to the user.
    """
    raise NotImplementedError()

  @abc.abstractmethod
  def train_few_shot_model(
      self, annotated_examples: Sequence[ZeroShotExample]
  ) -> AbstractFewShotClassifier:
    """Trains and returns a few shot classifier.

    Args:
      annotated_examples: A sequence of examples with user-provided labels.

    Returns:
      A trained `AbstractFewShotClassifier` instance ready for inference.
    """
    raise NotImplementedError()


class QueryProcessor(abc.ABC):
  """Abstract base class for embedding and scoring a query term."""

  @abc.abstractmethod
  def score_query(self, query_term: str, embeddings: np.ndarray) -> np.ndarray:
    """Embeds the query term and scores it against the embeddings."""
    raise NotImplementedError()


@dataclasses.dataclass(frozen=True)
class CropData:
  """Holds data for a single crop.

  Attributes:
    image_id: The unique identifier for the source image.
    crop: The image crop, expected to be a uint8 numpy array of shape (height,
      width, 3).
    bbox: The bounding box of the crop in the source image, expected to be a
      numpy array of shape (4,) with values [y_min, x_min, y_max, x_max]. The
      values are normalized to the range [0, 1].
  """

  image_id: bytes
  crop: np.ndarray
  bbox: np.ndarray


@dataclasses.dataclass
class DataHandler(abc.ABC):
  """Abstract base class for handling zero-shot data.

  Subclasses MUST set self.query_processor to a valid QueryProcessor instance.

  Attributes:
    query_processor: The query processor used for embedding and scoring the
      query term.
  """

  query_processor: Optional[QueryProcessor] = None

  @abc.abstractmethod
  def process_query(
      self,
      query_term: str,
      threshold: Optional[float] = None,
      max_examples: Optional[int] = None,
  ) -> Mapping[str, ZeroShotExample]:
    """Processes a text query and returns the top matching zero-shot examples.

    This method uses the `query_processor` to score the `query_term` against
    the zero-shot data.

    Either `threshold` or `max_examples` must be provided. If both are provided,
    only examples satisfying both conditions are returned.

    Args:
      query_term: The text query to process.
      threshold: If provided, only examples whose matching score (from the
        QueryProcessor) is above this threshold will be returned.
      max_examples: The maximum number of top-scoring examples to return.

    Returns:
      A mapping between example IDs and the `ZeroShotExample` objects for the
      top matching zero-shot examples. The example IDs are arbitrary strings
      that are used to identify the examples in the `get_crops` method.

    Raises:
      RuntimeError: If the DataHandler has not been initialized by calling
        `initialize()` before this method is called.
    """
    if self.query_processor is None:
      raise RuntimeError(
          "DataHandler is not initialized. Call initialize() first."
      )

    raise NotImplementedError()

  @abc.abstractmethod
  def get_crops(self, example_ids: Sequence[str]) -> Sequence[CropData]:
    """Returns the crops matching the given example ids.

    The example IDs provided should correspond to the keys in the mapping
    returned by the `process_query` method.

    Args:
      example_ids: A sequence of example IDs for which to retrieve crop data.
    """
    raise NotImplementedError()
